// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOK9ylereKYqX-0JdVwZIbCjJFLjUgg4M',
    appId: '1:527140711974:web:97616772e1c0da5f9740e7',
    messagingSenderId: '527140711974',
    projectId: 'origin-7b61f',
    authDomain: 'origin-7b61f.firebaseapp.com',
    storageBucket: 'origin-7b61f.firebasestorage.app',
    measurementId: 'G-39MTJYYFJZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDs_uXxbtrsSjaMB_THNm9BGVgBd4hNl_k',
    appId: '1:527140711974:android:e621c6f772a668979740e7',
    messagingSenderId: '527140711974',
    projectId: 'origin-7b61f',
    storageBucket: 'origin-7b61f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIdqC53FaTL06Z5oFFGl2lXzZKkNupHPE',
    appId: '1:527140711974:ios:853450890c102ad19740e7',
    messagingSenderId: '527140711974',
    projectId: 'origin-7b61f',
    storageBucket: 'origin-7b61f.firebasestorage.app',
    iosBundleId: 'com.example.jobHomepage1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIdqC53FaTL06Z5oFFGl2lXzZKkNupHPE',
    appId: '1:527140711974:ios:853450890c102ad19740e7',
    messagingSenderId: '527140711974',
    projectId: 'origin-7b61f',
    storageBucket: 'origin-7b61f.firebasestorage.app',
    iosBundleId: 'com.example.jobHomepage1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOK9ylereKYqX-0JdVwZIbCjJFLjUgg4M',
    appId: '1:527140711974:web:25c3e6fd8e534d9e9740e7',
    messagingSenderId: '527140711974',
    projectId: 'origin-7b61f',
    authDomain: 'origin-7b61f.firebaseapp.com',
    storageBucket: 'origin-7b61f.firebasestorage.app',
    measurementId: 'G-98Z4FYPDQM',
  );
}
